added a new Book model and functionality for it
Den-moroz/BookStore-api pull request #1
Opened 2023-08-15 13:07 UTC by Den-moroz

2023-08-15 13:34 UTC, padu12 approved these changes
Nice solution! Lets improve your HQL query)

2023-08-15 13:34 UTC, padu12 commented on src/main/java/core/basesyntax/bookstore/repository/impl/BookRepositoryImpl.java
> +                    .createQuery("SELECT b FROM Book b", Book.class)
```suggestion
                    .createQuery("FROM Book", Book.class)

```

2023-08-15 16:06 UTC, vovasalyha requested changes
Great work, take a look on few comments, also add maven wrapper to the project (see Bohdan's message in Slack)

2023-08-15 16:06 UTC, vovasalyha commented on src/main/java/core/basesyntax/bookstore/BookStoreApplication.java
> +    private BookService bookService;
You can pass this bean as a `commandLineRunner()` method param.

2023-08-15 16:06 UTC, vovasalyha commented on src/main/java/core/basesyntax/bookstore/repository/impl/BookRepositoryImpl.java
> +            transaction = session.beginTransaction();
You have Spring transaction manager already, use `@Transactional` instead of manual transactions handling

2023-08-15 16:06 UTC, vovasalyha commented on src/main/java/core/basesyntax/bookstore/service/impl/BookServiceImpl.java
> +    @Autowired
`@Autowired` is not required for constructor injection, Spring resolves it automatically.

2023-08-15 16:06 UTC, vovasalyha commented on src/main/java/core/basesyntax/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't create book " + book, e);
Try to avoid throwing a general RuntimeException.

2023-08-17 07:07 UTC, nacenik approved these changes
LGTM! 👍

2023-08-17 07:07 UTC, nacenik commented on src/main/java/core/basesyntax/bookstore/model/Book.java
> +@Table(name = "books")
https://medium.com/@centizennationwide/mysql-naming-conventions-e3a6f6219efe use singular work for table discription

2023-08-17 20:45 UTC, merged