added all necessary services for working with web
Den-moroz/BookStore-api pull request #2
Opened 2023-08-17 20:47 UTC by Den-moroz

2023-08-18 19:24 UTC, satori11111 approved these changes
Perfect, if mentor approved previous task you can rebase it from development to main according to [doc](https://mate-academy.github.io/jv-program-fulltime/07_spring_boot/git-strategy)

2023-08-21 07:44 UTC, nacenik requested changes
Good solution) Let's improve it a little bit) Also, resolve merge conflicts.

2023-08-21 07:44 UTC, nacenik commented on src/main/java/core/basesyntax/bookstore/config/MapperConfig.java
> +@org.mapstruct.MapperConfig(
You can import this annotation in the import statement 
```suggestion
@MapperConfig(
```

2023-08-21 07:44 UTC, nacenik commented on src/main/java/core/basesyntax/bookstore/controller/BookController.java
> +@RequestMapping(value = "/books")
I'd recommend you add "API" before your endpoints. It shows that your application is a REST
```suggestion
@RequestMapping(value = "/api/books")
```

2023-08-21 11:35 UTC, andrii-hoienko approved these changes
Good

2023-08-21 15:01 UTC, merged