added liquibase files and implemented soft delete logic
Den-moroz/BookStore-api pull request #3
Opened 2023-08-18 18:52 UTC by Den-moroz

2023-08-18 21:11 UTC, padu12 requested changes
Interesting solution. We have different implementations of the optional task and tbh I don't know which one is better🙃

And you forgot about some small thing)

2023-08-18 21:11 UTC, padu12 commented on src/main/java/core/basesyntax/bookstore/controller/BookController.java
you just forgot to add the update endpoint and the corresponding method in the service class

2023-08-19 14:49 UTC, padu12 approved these changes
LGTM✨

2023-08-21 11:45 UTC, andrii-hoienko requested changes
very nice, only one small issue

2023-08-21 11:45 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/bookstore/repository/book/BookSpecificationBuilder.java
> +        if (searchParametersDto.title() != null && searchParametersDto.title().length > 0) {
code duplication, hint: in stringUntils there are methods wich perform logic you need here

2023-08-21 13:25 UTC, Vasul-Pankiv approved these changes

2023-08-21 13:40 UTC, merged

2023-09-05 05:13 UTC, boroda4436 commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-book-table.yaml
empty line should be present at the EOF

2023-09-05 05:13 UTC, boroda4436 commented on src/main/java/core/basesyntax/bookstore/service/BookService.java
> +    BookDto updateById(Long id, CreateBookRequestDto bookRequestDto);
could be `update` not `updateById`