Add shopping cart, cart item and functionality for them
Den-moroz/BookStore-api pull request #9
Opened 2023-09-04 16:36 UTC by Den-moroz

2023-09-11 12:38 UTC, andrii-hoienko requested changes
Nice, some minor improvements required

2023-09-11 12:38 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/bookstore/service/impl/CartItemServiceImpl.java
> +    public CartItemDto save(CreateCartItemDto cartItemDto) {
There are too many responsibilities for one method here, please make this more SOLID

2023-09-11 12:38 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/bookstore/service/UserService.java
> +    User getUser();
What user do you get? It is not clear from method name

2023-09-11 12:38 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/08-create-cart-item-table.yaml
> +      author: denis
What if there are 2 denis in team?

2023-09-12 15:19 UTC, vovasalyha approved these changes

2023-09-12 15:19 UTC, vovasalyha commented on src/main/java/core/basesyntax/bookstore/model/ShoppingCart.java
> +    private List<CartItem> cartItems;
It's better to initialize collections here, so Hibernate can choose a right implementation of proxied collection

2023-09-12 15:30 UTC, merged